Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).


In [1]:

import numpy as np

N=int(input())

lst=list(range(N,0,-1))
arr = np.array(lst) 

print ("List: ", lst, type(lst)) 
  
print ("Array: ", arr, type(arr))

10
List:  [10, 9, 8, 7, 6, 5, 4, 3, 2, 1] <class 'list'>
Array:  [10  9  8  7  6  5  4  3  2  1] <class 'numpy.ndarray'>


Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [2]:

N=int(input())
mtrx=np.diag(np.arange(N, -1, -1), k=0)
print(mtrx)

print('Сумма диагонали:',np.sum(mtrx))

5
[[5 0 0 0 0 0]
 [0 4 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 0]]
Сумма диагонали: 15



Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [3]:
a = np.array( [ [4, 2,1], [1, 3,0], [5,4,9] ] )
b = np.array( [4, 12,-3] )
from numpy import linalg
linalg.solve(a, b)

array([-0.64556962,  4.21518987, -1.84810127])

Задание 4

In [5]:

users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])


Найдите самого похожего пользователя. Т. е. посчитайте косинусное расстояние между этим пользователем и всеми пользователями из массива user_stats

In [7]:
def cosine( a, b ):

    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

b=next_user_stats
i=0
user_dict={}
for user in users_stats:
    i+=1
    user_dict.update({i:cosine(user,b)})
    #print(round(cosine(user,b),2))
max(user_dict,key=user_dict.get)

8